### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by AeSix** [OopsieWoopsie/BanAnnouncer#1]
So, trying to get BanAnnouncer working... 
It gave me this error:
```
02:38:54 [INFO] [Spicord] Loaded 1 bots, 0 disabled.
02:38:54 [INFO] [Spicord] [DEBUG] [Loader] Loaded library 'JDA-3.8.3_460-withDependencies.jar'.
02:38:54 [INFO] [Spicord] Registered addon 'Server Information' (spicord::info) by OopsieWoopsie
02:38:54 [INFO] [Spicord] Registered addon 'Plugin List' (spicord::plugins) by OopsieWoopsie
02:38:54 [INFO] [Spicord] Registered addon 'Player List' (spicord::players) by OopsieWoopsie
02:38:54 [INFO] [Spicord] [DEBUG] Disabling JDA's messages...
02:38:54 [INFO] [Spicord] [DEBUG] Successfully disabled JDA's messages.
02:38:54 [INFO] [Spicord] Starting the bots...
02:38:54 [INFO] [Spicord] Starting bot 'default'.
02:38:54 [SEVERE] Exception in thread "Thread-38"
02:38:54 [SEVERE] java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticMDCBinder.getMDCA()Lorg/slf4j/spi/MDCAdapter;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/MDC, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticMDCBinder, have different Class objects for the type org/slf4j/spi/MDCAdapter used in the signature
02:38:54 [SEVERE]     at org.slf4j.MDC.bwCompatibleGetMDCAdapterFromBinder(MDC.java:99)
02:38:54 [SEVERE]     at org.slf4j.MDC.<clinit>(MDC.java:108)
02:38:54 [SEVERE]     at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:207)
02:38:54 [SEVERE]     at net.dv8tion.jda.core.JDABuilder.build(JDABuilder.java:913)
02:38:54 [SEVERE]     at eu.mcdb.spicord.bot.DiscordBot.startBot(DiscordBot.java:105)
02:38:54 [SEVERE]     at eu.mcdb.spicord.bot.DiscordBotLoader$1.run(DiscordBotLoader.java:40)
02:38:54 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
```
Versions:
  BanAnnouncer: 1.0.2 F1  (From Github)
  Spicord: 1.0.4-SNAPSHOT (from SpigotMC)
  AdvancedBans 2.1.5 (from SpigotMC)
BungeeCord 1.14 (build 1414)

note: I have no 1.14 back-end servers, am not using Waterfall/Travertine, etc, just md_5's BungeeCord.  I have no other errors in the logs.

**Comment by OopsieWoopsie** [comment]
I forget to add the GitHub webhook to the Discord server, I just logged in to my GH account and saw this (Sorry).

I cannot reproduce the error on my machine.

What OS are you using?
Are you using another plugin which has JDA integrated on it? I mean, another plugin with discord integration.
