### ISSUE TITLE
Broken on java 14

### ISSUE THREAD

**Issue by lukeeexd** [OopsieWoopsie/BanAnnouncer#10]
`[14:28:01 ERROR]: Could not load 'plugins/BanAnnouncer_2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Spicord
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:239) ~[patched_1.15.2.jar:git-Tuinity-"b41ed5c"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Tuinity-"b41ed5c"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Tuinity-"b41ed5c"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Tuinity-"b41ed5c"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
`

**Comment by Blocksnmore** [comment]
[14:28:01 ERROR]: Could not find user lukeeeexd in folder 'read-the-error'
read the logs before reporting an issue, your server is missing spicord and from what it looks like your running spigot not paper

**Comment by OopsieWoopsie** [comment]
Answered [here](https://www.spigotmc.org/threads/banannouncer-discord.360501/page-2#post-3748002).
Closed due to inactivity.
