### ISSUE TITLE
[Craft Scheduler Thread - 138/ERROR]: Could not pass event PunishmentEvent to BanAnnouncer v2.0.1

### ISSUE THREAD

**Issue by ggggggbgg** [OopsieWoopsie/BanAnnouncer#11]
this plugin is successfully loaded,but when i run /ban example example , it pop up this error:
[Craft Scheduler Thread - 138/ERROR]: Could not pass event PunishmentEvent to BanAnnouncer v2.0.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:508) ~[spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]
at me.leoko.advancedban.bukkit.BukkitMethods.callPunishmentEvent(BukkitMethods.java:347) ~[?:?]
at me.leoko.advancedban.utils.Punishment.create(Punishment.java:166) ~[?:?]
at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46) ~[?:?]
at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:72) ~[?:?]
at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:18) ~[?:?]
at me.leoko.advancedban.utils.Command.execute(Command.java:404) ~[?:?]
at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: net.dv8tion.jda.core.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE
at net.dv8tion.jda.core.entities.impl.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:304) ~[?:?]
at net.dv8tion.jda.core.entities.impl.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:296) ~[?:?]
at net.dv8tion.jda.core.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:330) ~[?:?]
at eu.mcdb.spicord.embed.EmbedSender.prepare(EmbedSender.java:29) ~[?:?]
at eu.mcdb.ban_announcer.BanAnnouncer.lambda$null$2(BanAnnouncer.java:198) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_242]
at eu.mcdb.ban_announcer.BanAnnouncer.lambda$sendDiscordMessage$3(BanAnnouncer.java:192) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:191) ~[?:?]
at eu.mcdb.ban_announcer.BanAnnouncer.sendBanMessage(BanAnnouncer.java:171) ~[?:?]
at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:70) ~[?:?]
at eu.mcdb.ban_announcer.listener.AdvancedBan.onPunishmentAction(AdvancedBan.java:73) ~[?:?]
at eu.mcdb.ban_announcer.bukkit.listener.AdvancedBanListener.onPunishment(AdvancedBanListener.java:30) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.jar:git-Spigot-f39a89e-4633e6c]

my server is 1.15,i run this command from console,using advancedban v2.1.8

**Comment by Audition-CSBlock** [comment]
im still having issues with this, why did this get closed???! @ggggggbgg
