### ISSUE TITLE
Help ?

### ISSUE THREAD

**Issue by TreeV2** [OopsieWoopsie/BanAnnouncer#16]
[BanAnnouncer] Task #9 for BanAnnouncer v2.0.1 generated an exception
java.lang.NoClassDefFoundError: eu/mcdb/util/ServerType
        at eu.mcdb.ban_announcer.config.Config$1.<clinit>(Config.java:68) ~[?:?]
        at eu.mcdb.ban_announcer.config.Config.<init>(Config.java:68) ~[?:?]
        at eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit.enable(BanAnnouncerBukkit.java:41) ~[?:?]
        at eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit.lambda$onEnable$0(BanAnnouncerBukkit.java:37) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: eu.mcdb.util.ServerType
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        ... 11 more

**Comment by OopsieWoopsie** [comment]
You need to keep BanAnnouncer and Spicord updated, because API changes may happen between releases and just updating one plugin will lead to errors like this
