### ISSUE TITLE
Could not pass event PunishmentEvent to BanAnnouncer v2.0.2

### ISSUE THREAD

**Issue by Audition-CSBlock** [OopsieWoopsie/BanAnnouncer#18]
Not a duplicate of #11 since that issue included this line:
`Caused by: net.dv8tion.jda.core.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE`
And mine does not include any "caused by:" lines, so i have no idea what is causing this error,

Any help is appreciated.

```java
java.lang.IllegalArgumentException: URL must be a valid http(s) or attachment url.
        at net.dv8tion.jda.core.utils.Checks.check(Checks.java:38) ~[?:?]
        at net.dv8tion.jda.core.EmbedBuilder.urlCheck(EmbedBuilder.java:772) ~[?:?]
        at net.dv8tion.jda.core.EmbedBuilder.setFooter(EmbedBuilder.java:670) ~[?:?]
        at eu.mcdb.spicord.embed.Embed.toJdaEmbed(Embed.java:389) ~[?:?]
        at eu.mcdb.spicord.embed.EmbedSender.prepare(EmbedSender.java:35) ~[?:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.lambda$null$2(BanAnnouncer.java:198) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.lambda$sendDiscordMessage$3(BanAnnouncer.java:192) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:191) ~[?:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.sendKickMessage(BanAnnouncer.java:138) ~[?:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:72) ~[?:?]
        at eu.mcdb.ban_announcer.listener.AdvancedBan.onPunishmentAction(AdvancedBan.java:73) ~[?:?]
        at eu.mcdb.ban_announcer.bukkit.listener.AdvancedBanListener.onPunishment(AdvancedBanListener.java:30) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor124.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-184]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.2.jar:git-Paper-184]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-184]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-184]
        at me.leoko.advancedban.bukkit.BukkitMethods.callPunishmentEvent(BukkitMethods.java:368) ~[?:?]
        at me.leoko.advancedban.utils.Punishment.create(Punishment.java:151) ~[?:?]
        at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46) ~[?:?]
        at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:72) ~[?:?]
        at me.leoko.advancedban.utils.Command.lambda$static$0(Command.java:104) ~[?:?]
        at me.leoko.advancedban.utils.Command.execute(Command.java:552) ~[?:?]
        at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-184]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-184]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-184]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Audition-CSBlock** [comment]
I fixed it myself after lots of debugging (I don't really know java), I found that the "icon_url" couldn't be empty so i deleted the whole "footer" part of the embed files.
